---
- name: Deploy Docker container on localhost
  hosts: localhost
  tasks:
    - name: Pull the Docker image from DockerHub
      docker_image:
        name: wajdimansour/myapp
        tag: latest
        source: pull

    - name: Run the Docker container
      docker_container:
        name: myapp_container
        image: sadokgaied/myapp:latest
        state: started
        ports:
          - "8080:8080"
